name: TeaChat
version: '1.0.1-Beta5'
main: top.heartstring.teachat.BukkitCore
depend: [PlaceholderAPI]
softdepend: [DragonCore]
api-version: 1.13
commands:
  teachat:
    aliases: [chat]
permissions:
  teachat.*:
    default: op
    children:
      teachat.admin.*: true
      teachat.channel.*: true
  teachat.channel:
    default: true
  teachat.title:
    default: true
  teachat.admin.reload:
    default: op
